# Generated by Django 5.2.6 on 2025-10-17 10:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceslist',
            name='image',
            field=cloudinary.models.CloudinaryField(default=2, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
