# Generated by Django 4.2 on 2025-09-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='serviceslist',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
