# Generated by Django 5.2.6 on 2025-10-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceslist',
            name='id',
        ),
        migrations.AlterField(
            model_name='serviceslist',
            name='name',
            field=models.CharField(blank=True, default='Treatment', max_length=256, primary_key=True, serialize=False),
        ),
    ]
