# Generated by Django 5.2.6 on 2025-10-17 10:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceslist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceslist',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
    ]
