# Generated by Django 5.2.6 on 2025-10-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_serviceslist_id_alter_serviceslist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceslist',
            name='name',
            field=models.CharField(blank=True, max_length=256, primary_key=True, serialize=False),
        ),
    ]
