# Generated by Django 5.2.6 on 2025-10-21 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_alter_serviceslist_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.TimeField()),
                ('appointment_date', models.DateField()),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(default='Guest', max_length=96)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('deposit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('final_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceslist')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Appointments',
                'ordering': ['-appointment_date', '-appointment_time'],
                'unique_together': {('service', 'appointment_date', 'appointment_time')},
            },
        ),
    ]
