# Generated by Django 5.2.6 on 2025-10-06 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_remove_serviceslist_id_alter_serviceslist_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointment_time', models.TimeField()),
                ('appointment_date', models.DateField()),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(default='Guest', max_length=96)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_phone', models.IntegerField(default=0)),
                ('deposit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Treatment', to='services.serviceslist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
