# Generated by Django 5.2.6 on 2025-10-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='user_name',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
    ]
