# Generated by Django 5.2.6 on 2025-10-07 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('services', '0003_remove_serviceslist_id_alter_serviceslist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceslist'),
        ),
    ]
