# Generated by Django 5.2.6 on 2025-10-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('FAILED', 'Failed/Expired')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='appointments',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
