# Generated by Django 5.2.6 on 2025-10-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointments_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='deposit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='appointments',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='appointments',
            name='user_phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='user_name',
            field=models.CharField(default='Guest', max_length=96),
        ),
    ]
