# Generated by Django 5.2.6 on 2025-10-24 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointments_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='id',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
