# Generated by Django 5.2.6 on 2025-10-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointments_id_alter_appointments_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('BALANCE', 'Paid'), ('FAILED', 'Failed/Expired'), ('DEPOSIT', 'Partial Paid')], default='PENDING', max_length=20),
        ),
    ]
