# Generated by Django 5.2.6 on 2025-10-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointments_deposit_cost_appointments_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='service',
            new_name='name',
        ),
    ]
