# Generated by Django 5.2.6 on 2025-10-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointments_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='deposit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
