# Generated by Django 5.2.6 on 2025-10-02 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_rename_service_appointments_name'),
        ('services', '0003_remove_serviceslist_id_alter_serviceslist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Treatment', to='services.serviceslist'),
        ),
    ]
